name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
#          username: ${{ github.actor }}
#          password: ${{ secrets.PAT }}
#          registry: ghcr.io
          username: sandronidi
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sandronidi/anibot
          tag_with_ref: true
          tags: latest
